// TEST-BOOTSTRAP:STUB
//! Showcase tests for lumina — generated by /test-bootstrap.
//! Each slot is named in its header comment.
//!
//! Dependencies required in [dev-dependencies]:
//!   rstest            = "0.26"
//!   pretty_assertions = "1.4"
//!   proptest          = "1.9"
//!   tempfile          = "3"   (already a [dependencies] entry in lumina/Cargo.toml)

use lumina::domain::{Severity, Status};
use lumina::error::AppError;
use pretty_assertions::assert_eq;
use proptest::prelude::*;
use rstest::rstest;

// ---------------------------------------------------------------------------
// 1. AAA happy path (bound: lumina::error::AppError Display)
//    Characterized from lumina/src/error.rs:42 — NotFound(m) => "not found: {m}"
// ---------------------------------------------------------------------------
#[test]
fn apperror_not_found_display_returns_prefixed_message() {
    // arrange
    let err = AppError::NotFound("missing".to_owned());

    // act
    let msg = err.to_string();

    // assert
    assert_eq!(msg, "not found: missing");
}

// ---------------------------------------------------------------------------
// 2. Parameterised / table-driven (bound: lumina::domain::Severity serde wire form)
//    Uses rstest #[rstest] + #[case(...)]; 4 cases, one per variant.
//    Wire form confirmed from src/domain.rs: #[serde(rename_all = "snake_case")]
// ---------------------------------------------------------------------------
#[rstest]
#[case(Severity::Critical,   "\"critical\"")]
#[case(Severity::Major,      "\"major\"")]
#[case(Severity::Minor,      "\"minor\"")]
#[case(Severity::Suggestion, "\"suggestion\"")]
fn severity_serialises_to_snake_case(#[case] variant: Severity, #[case] expected_json: &str) {
    let wire = serde_json::to_string(&variant).unwrap();
    assert_eq!(wire, expected_json);
}

// ---------------------------------------------------------------------------
// 3. Error-path (bound: lumina::domain::Status serde rejection)
//    "nonsense" is not a valid Status variant; serde reports "unknown variant".
// ---------------------------------------------------------------------------
#[test]
fn status_rejects_unknown_variant_with_descriptive_error() {
    let result = serde_json::from_str::<Status>("\"nonsense\"");
    assert!(result.is_err(), "expected Err for unknown status variant");
    let msg = result.unwrap_err().to_string();
    assert!(
        msg.contains("unknown variant"),
        "expected 'unknown variant' in error message, got: {msg}"
    );
}

// ---------------------------------------------------------------------------
// 4. Per-test fixture with tempdir lifecycle (synthetic — no fitting candidate)
//    tempfile::TempDir's Drop impl removes the directory when it goes out of scope.
// ---------------------------------------------------------------------------
#[test]
fn tempdir_write_read_round_trip() {
    let dir = tempfile::TempDir::new().expect("failed to create temp dir");
    let file_path = dir.path().join("hello.txt");

    std::fs::write(&file_path, b"lumina").expect("write failed");
    let contents = std::fs::read(&file_path).expect("read failed");

    assert_eq!(contents, b"lumina");
    // dir dropped here — directory and file are deleted by TempDir::drop
}

// ---------------------------------------------------------------------------
// 5. Mock at smallest boundary (synthetic — no obvious mockable trait seam in lumina)
//    Defines a minimal Greeter trait + stub inside this file to demonstrate
//    the mock-at-smallest-boundary pattern.
// ---------------------------------------------------------------------------
trait Greeter {
    fn greet(&self, who: &str) -> String;
}

struct RealGreeter;
impl Greeter for RealGreeter {
    fn greet(&self, who: &str) -> String {
        format!("Hello, {who}!")
    }
}

struct StubGreeter {
    fixed_response: &'static str,
}
impl Greeter for StubGreeter {
    fn greet(&self, _who: &str) -> String {
        self.fixed_response.to_owned()
    }
}

fn welcome<G: Greeter>(g: &G) -> String {
    g.greet("world")
}

#[test]
fn welcome_delegates_to_greeter_stub() {
    let stub = StubGreeter { fixed_response: "stub-response" };
    assert_eq!(welcome(&stub), "stub-response");
}

#[test]
fn welcome_delegates_to_real_greeter() {
    let real = RealGreeter;
    assert_eq!(welcome(&real), "Hello, world!");
}

// ---------------------------------------------------------------------------
// 6. Property-based (bound: lumina::domain::Severity serde round-trip)
//    proptest prop_oneof! over all four variants; from_str(to_str(s)) == s.
// ---------------------------------------------------------------------------
proptest! {
    #[test]
    fn severity_serde_round_trip(s in prop_oneof![
        Just(Severity::Critical),
        Just(Severity::Major),
        Just(Severity::Minor),
        Just(Severity::Suggestion),
    ]) {
        let wire = serde_json::to_string(&s).unwrap();
        let back: Severity = serde_json::from_str(&wire).unwrap();
        prop_assert_eq!(s, back);
    }
}
