// TEST-BOOTSTRAP:STUB
// Showcase tests for lumina/web — generated by /test-bootstrap.
// Each slot is named in its header comment.
//
// Dev deps required (already in package.json):
//   @types/bun  — types for `bun:test`
//   fast-check  — property-based testing
//
// Runner: `bun test` (from lumina/web/).

import { afterEach, beforeEach, describe, expect, mock, test } from 'bun:test'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import * as fc from 'fast-check'

import { asStatus, effortLabel, kindLabel, statusLabel } from '../composables/useDisplay'
import { fetchTree } from '../api'

// ---------------------------------------------------------------------------
// 1. AAA happy path (bound: useDisplay::statusLabel)
//    Characterized from lumina/web/src/composables/useDisplay.ts:29 —
//    statusLabel('done') => 'DONE'.
// ---------------------------------------------------------------------------
test('statusLabel returns the uppercase display label for a known backend status', () => {
  // arrange
  const backend = 'done'

  // act
  const label = statusLabel(backend)

  // assert
  expect(label).toBe('DONE')
})

// ---------------------------------------------------------------------------
// 2. Parameterised / table-driven (bound: useDisplay::effortLabel)
//    Uses bun:test's test.each. Five rows covering the three valid wire
//    forms plus invalid/null/undefined fallthroughs.
// ---------------------------------------------------------------------------
test.each<[string | null | undefined, string | null]>([
  ['s', 'S'],
  ['m', 'M'],
  ['l', 'L'],
  ['x', null],
  [null, null],
  [undefined, null],
])('effortLabel(%p) === %p', (effort, expected) => {
  expect(effortLabel(effort)).toBe(expected)
})

// ---------------------------------------------------------------------------
// 3. Error-path (bound: useDisplay::asStatus)
//    Invalid backend strings return null rather than throwing — assert the
//    null contract, not an exception.
// ---------------------------------------------------------------------------
test('asStatus returns null for an unknown backend status', () => {
  const result = asStatus('nonsense')
  expect(result).toBeNull()
})

// ---------------------------------------------------------------------------
// 4. Per-test fixture with tempdir lifecycle (synthetic — web code doesn't
//    touch the filesystem). Demonstrates the per-test mkdtemp + rmSync teardown
//    pattern using Node fs.
// ---------------------------------------------------------------------------
describe('tempdir lifecycle', () => {
  let dir: string

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'lumina-showcase-'))
  })

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true })
  })

  test('write/read round-trip works inside the tempdir', () => {
    const filePath = path.join(dir, 'hello.txt')
    fs.writeFileSync(filePath, 'lumina')
    expect(fs.readFileSync(filePath, 'utf8')).toBe('lumina')
  })
})

// ---------------------------------------------------------------------------
// 5. Mock at smallest boundary (bound: api::fetchTree mocking globalThis.fetch)
//    fetchTree() calls fetch('/api/work-items') once; mock that single edge.
//    Per-test reset of globalThis.fetch keeps the suite order-independent.
// ---------------------------------------------------------------------------
describe('fetchTree (mock global fetch)', () => {
  let originalFetch: typeof globalThis.fetch

  beforeEach(() => {
    originalFetch = globalThis.fetch
  })

  afterEach(() => {
    globalThis.fetch = originalFetch
  })

  test('returns the parsed JSON tree on 200', async () => {
    // Complete WorkItemNode fixture — every field is required after the R27
    // schema-validation tightening at the wire boundary (api.ts::handle). A
    // partial fixture would now fail with a contract-violation Error.
    const fakeNodes = [
      {
        id: 'p1',
        kind: 'project',
        parent_id: null,
        title: 'lumina',
        body: null,
        status: 'todo',
        position: null,
        attributes: null,
        relevance: null,
        effort: null,
        complexity: null,
        origin: null,
        closure_gate: null,
        blocked_by_question_id: null,
        enabling_option_id: null,
        created_at: '2026-05-25T00:00:00Z',
        updated_at: '2026-05-25T00:00:00Z',
        children: [],
      },
    ]
    globalThis.fetch = mock(
      async () =>
        new Response(JSON.stringify(fakeNodes), {
          status: 200,
          headers: { 'Content-Type': 'application/json' },
        }),
    ) as typeof globalThis.fetch

    const tree = await fetchTree()
    expect(tree).toEqual(fakeNodes as unknown as Awaited<ReturnType<typeof fetchTree>>)
  })

  test('throws with the server error message on a non-2xx response', async () => {
    globalThis.fetch = mock(
      async () =>
        new Response(
          JSON.stringify({ error: { kind: 'not_found', message: 'missing' } }),
          {
            status: 404,
            statusText: 'Not Found',
            headers: { 'Content-Type': 'application/json' },
          },
        ),
    ) as typeof globalThis.fetch

    await expect(fetchTree()).rejects.toThrow(/API request failed: missing/)
  })
})

// ---------------------------------------------------------------------------
// 6. Property-based (bound: useDisplay::kindLabel idempotence)
//    kindLabel(s) returns s.toUpperCase(); applying it again must be a no-op.
// ---------------------------------------------------------------------------
test('kindLabel is idempotent — kindLabel(kindLabel(s)) === kindLabel(s)', () => {
  fc.assert(
    fc.property(fc.string(), (s) => {
      const once = kindLabel(s)
      const twice = kindLabel(once)
      return once === twice
    }),
  )
})
